[workspace]
members = [
  "api-admin",
  "api-internal",
  "api-private",
  "api-public",
  "core",
  "db",
  "app",
  "settings",
]

resolver = "2"

[profile.release]
debug = 1
incremental = true
lto = "off"
