debug = true
use_opentelemetry = false

[cookies]
http_only = false
secure = false

[database]
database = "cardbox"
host = "localhost"
password = "cardbox"
user = "cardbox"
pool_size = 2
ssl_validate = false

[server]
host = "localhost"
port = 9110
use_ssl = false
use_h1 = false

[accesso]
url = "http://localhost:9015"
client_id = '00000000-0000-4000-acce-000000009200'
redirect_back_url = "https://0.0.0.0:9100/accesso/done"
client_secret = "w3msPYIg2lnnvEccpDONSkHFHED658zkzYyfiuQWyql6gKVteF6N"
ssl_validate = false
