debug = true
use_opentelemetry = false

[cookies]
http_only = false
secure = false

[database]
database = "cardbox"
host = "localhost"
password = "cardbox"
user = "cardbox"
port = 5433
pool_size = 2
ssl_validate = false

[server]
host = "localhost"
port = 9110

[accesso]
url = "https://accesso.local:3000"
client_id = '00000000-0000-4000-acce-000000009100'
redirect_back_url = "https://cardbox.local:5000/oauth-done"
client_secret = "CardboxDev"
ssl_validate = false
